# Generated by Django 6.0.1 on 2026-08-05 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0006_report_sellerverification_systemsettings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='category',
            field=models.CharField(blank=True, choices=[('Academic', 'Academic'), ('Competitive Exams', 'Competitive Exams'), ('School', 'School'), ('College', 'College'), ('Engineering', 'Engineering'), ('Medical', 'Medical'), ('Novel', 'Novel'), ('Story', 'Story'), ('Comics', 'Comics'), ('History', 'History'), ('Science', 'Science'), ('Programming', 'Programming'), ('Other', 'Other')], max_length=100, null=True),
        ),
    ]
